<div class="container">
	<div class="row">
		<class class="col-xs-9">
			<div class="login">
				<div class="login-screen">
					<div class="login-icon">
						<img src="images/login/icon.png" alt="">
						<h4>Please login</h4>
					</div>
					<div class="login-form">
            <div class="form-group">
              <input type="text" class="form-control login-field" value="" placeholder="Enter your name" id="login-name">
              <label class="login-field-icon fui-user" for="login-name"></label>
            </div>

            <div class="form-group">
              <input type="password" class="form-control login-field" value="" placeholder="Password" id="login-pass">
              <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>

            <a class="btn btn-primary btn-lg btn-block" href="#">Login</a>
            <a class="login-link" href="#">Lost your password?</a>
          </div>
				</div>
			</div>
		</class>
	</div>
</div>
