<div class="container">
    <div class="row">
        <class class="col-xs-9 col-xs-offset-3">
            <div class="login">
                <div class="login-screen">
                    <div class="login-icon">
                        <img src="../images/login/icon.png" alt="">
                        <h4>Please login</h4>
                    </div>
                    <div class="login-form">
                        <form
                            action="<?= $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'login')) ?>"
                            method="POST">
                            <div class="form-group">
                                <input type="text" class="form-control login-field" value=""
                                       placeholder="Enter your login" id="login-name" name="login"/>
                                <label class="login-field-icon fui-user" for="login-name"></label>
                            </div>

                            <div class="form-group">
                                <input type="password" class="form-control login-field" value="" placeholder="Password"
                                       id="login-pass" name="password"/>
                                <label class="login-field-icon fui-lock" for="login-pass"></label>
                            </div>

                            <div class="submit-group">
                                <input type="submit" class="btn btn-primary" name="submit" value="Login"/>
                                <a class="login-link" href="#">Lost your password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </class>
    </div>
</div>
